name: Ý tưởng game
description: Một game bạn muốn chơi ở đây
labels: [game idea, needs-triage]
body:
  - type: input
    id: name
    attributes:
      label: Game
      placeholder: Cờ tướng
    validations:
      required: true
  - type: input
    id: players
    attributes:
      label: Số người chơi
      placeholder: "2"
  - type: textarea
    id: rules
    attributes:
      label: Luật chơi, hoặc link tới luật
  - type: checkboxes
    id: help
    attributes:
      label: Giúp sức
      options:
        - label: Mình muốn tự làm game này (xem CONTRIBUTING.md)
