// Finds every game in games/* and builds the libraries the server runs:
// @psc/sdk, each game's server part (src/index.ts), then @psc/shared.
//   node scripts/libs.mjs             generate the game list + build
//   node scripts/libs.mjs --watch     same, then rebuild on change (npm run dev)
//   node scripts/libs.mjs --generate  only write the game list (npm install runs this)
// The game list is packages/shared/src/generated/games.ts (gitignored): one static import per
// game, so tsc, Vite and Nest all see it. Adding a game folder is enough; nothing to register.
import { spawnSync } from 'node:child_process';
import { existsSync, mkdirSync, readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { createRequire } from 'node:module';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const args = process.argv.slice(2);

const ids = findGames();
writeGameList(ids);
if (args.includes('--generate')) process.exit(0);

const tsc = createRequire(import.meta.url).resolve('typescript/bin/tsc');
const projects = [
  'packages/sdk/tsconfig.build.json',
  ...ids.map((id) => `games/${id}/tsconfig.build.json`),
  'packages/shared/tsconfig.build.json',
];
const watch = args.includes('--watch') ? ['--watch', '--preserveWatchOutput'] : [];
const res = spawnSync(process.execPath, [tsc, '-b', ...projects, ...watch], {
  cwd: root,
  stdio: 'inherit',
});
process.exit(res.status ?? 1);

/** Game ids (= folder names), checked so mistakes fail here with a clear message. */
function findGames() {
  const dir = join(root, 'games');
  const found = [];
  const problems = [];
  for (const id of readdirSync(dir).sort()) {
    const folder = join(dir, id);
    const pkgPath = join(folder, 'package.json');
    if (!existsSync(pkgPath)) continue;
    const pkg = JSON.parse(readFileSync(pkgPath, 'utf8'));
    if (!/^[a-z0-9]+(-[a-z0-9]+)*$/.test(id)) problems.push(`games/${id}: use a kebab-case name`);
    if (pkg.name !== `@psc/game-${id}`)
      problems.push(`games/${id}/package.json: "name" must be "@psc/game-${id}"`);
    for (const file of ['src/index.ts', 'src/client.ts', 'tsconfig.build.json']) {
      if (!existsSync(join(folder, file))) problems.push(`games/${id}: missing ${file}`);
    }
    if (!existsSync(join(root, 'node_modules/@psc', `game-${id}`)))
      problems.push(`games/${id}: not installed yet, run npm install`);
    found.push(id);
  }
  if (problems.length) {
    console.error(problems.map((p) => `✗ ${p}`).join('\n'));
    process.exit(1);
  }
  return found;
}

function writeGameList(ids) {
  const name = (id) => id.replace(/-(\w)/g, (_, c) => c.toUpperCase());
  const source = [
    '// Generated by scripts/libs.mjs from games/*. Do not edit; it is rewritten on every build.',
    "import type { AnyGamePlugin } from '@psc/sdk';",
    ...ids.map((id) => `import ${name(id)} from '@psc/game-${id}';`),
    '',
    `export const plugins: AnyGamePlugin[] = [${ids.map(name).join(', ')}];`,
    '',
  ].join('\n');
  const file = join(root, 'packages/shared/src/generated/games.ts');
  if (existsSync(file) && readFileSync(file, 'utf8') === source) return;
  mkdirSync(dirname(file), { recursive: true });
  writeFileSync(file, source);
}
