"""Bake flush enamel owner strips and porcelain buildings with the board's Blender camera.

  blender -b -t 4 --python games/co-ty-phu-classic/sources/render_deed_layers.py

The atlas contains per-square sprites, not flat colored polygons. All lighting, bevels,
occlusion and transparent shadows are rendered once. Game state only selects atlas frames.
"""

from __future__ import annotations

import json
import math
import runpy
import sys
from pathlib import Path

import bpy
from PIL import Image, ImageChops, ImageDraw, ImageFilter

ROOT = Path(__file__).resolve().parents[1]
sys.argv.append("--geometry-only")
board = runpy.run_path(str(ROOT / "sources" / "render_board_25d.py"))
scene = bpy.context.scene
for obj in scene.objects:
    if obj.type not in ("LIGHT", "CAMERA"):
        obj.hide_render = True
scene.cycles.samples = 64
scene.cycles.use_denoising = False

PREVIEW = ROOT.parents[1] / ".blender"
ASSETS = ROOT / "assets"
SQUARES = board["SQUARES"]
WIDTH, HEIGHT = board["WIDTH"], board["HEIGHT"]
CX, CY, CW, CH = (board[name] for name in ("CROP_X", "CROP_Y", "CROP_WIDTH", "CROP_HEIGHT"))
DEEDS = [i for i, (kind, _) in enumerate(SQUARES) if kind in ("street", "station", "power", "water")]
STREETS = [i for i, (kind, _) in enumerate(SQUARES) if kind == "street"]
COLORS = [0xDF6554, 0x5793D3, 0x60AF72, 0xE6BE52]


def srgb(channel):
    c = channel / 255
    return c / 12.92 if c <= 0.04045 else ((c + 0.055) / 1.055) ** 2.4


def coated(name, rgb, roughness):
    mat = board["material"](name, rgb, 0.10, roughness)
    shader = mat.node_tree.nodes.get("Principled BSDF")
    (shader.inputs.get("Coat Weight") or shader.inputs["Clearcoat"]).default_value = 0.4
    (shader.inputs.get("Coat Roughness") or shader.inputs["Clearcoat Roughness"]).default_value = 0.20
    return mat


enamel = coated("Player enamel inlay", (0.7, 0.1, 0.08), 0.3)
porcelain = coated("White porcelain houses", (0.92, 0.94, 0.98), 0.24)


def uv(square, along, depth):
    u0, v0, u1, v1 = board["square_bounds"](square)
    side = board["tile_side"](square)
    if side == "bottom":
        u, v = along, 1 - depth
    elif side == "left":
        u, v = depth, along
    elif side == "top":
        u, v = along, depth
    else:
        u, v = 1 - depth, along
    return u0 + (u1 - u0) * u, v0 + (v1 - v0) * v


def xy(square, along, depth):
    u, v = uv(square, along, depth)
    return (u - 0.5) * 4, (0.5 - v) * 4


def dimensions(square):
    u0, v0, u1, v1 = board["square_bounds"](square)
    w, h = (u1 - u0) * 4, (v1 - v0) * 4
    return (w, h) if board["tile_side"](square) in ("bottom", "top") else (h, w)


badges = []
for square in DEEDS:
    corners = [xy(square, a, d) for a, d in ((0, .9), (1, .9), (1, 1), (0, 1))]
    xs, ys = zip(*corners)
    bpy.ops.mesh.primitive_cube_add(size=1, location=((min(xs) + max(xs)) / 2, (min(ys) + max(ys)) / 2, 0.042))
    obj = bpy.context.object
    obj.name = f"Flush enamel strip {square}"
    obj.dimensions = (max(xs) - min(xs), max(ys) - min(ys), 0.007)
    bpy.ops.object.transform_apply(location=False, rotation=False, scale=True)
    bevel = obj.modifiers.new("Fine enamel highlight", "BEVEL")
    bevel.width, bevel.segments = 0.0009, 3
    obj.modifiers.new("Face normals", "WEIGHTED_NORMAL")
    obj.data.materials.append(enamel)
    badges.append(obj)

rects = [None] * 40
for square in DEEDS:
    points = [board["project"](*uv(square, a, d)) for a, d in ((0, .89), (1, .89), (1, 1.01), (0, 1.01))]
    xs, ys = zip(*points)
    x0, y0 = math.floor(min(xs) * CW) - 5, math.floor(min(ys) * CH) - 5
    x1, y1 = math.ceil(max(xs) * CW) + 5, math.ceil(max(ys) * CH) + 5
    rects[square] = (x0, y0, x1 - x0, y1 - y0)

normalized = [None if rect is None else [round(rect[0] / CW, 8), round(rect[1] / CH, 8), round(rect[2] / CW, 8), round(rect[3] / CH, 8)] for rect in rects]
(ROOT / "src/scenes/board/deedLayerGeometry.ts").write_text("// Generated by sources/render_deed_layers.py; rectangles in board-image coordinates.\nexport const DEED_LAYER_RECTS = " + json.dumps(normalized, indent=2) + " as const;\n")

sprites = []


def render_frames(prefix, squares):
    png = PREVIEW / f"deed-{prefix}.png"
    if "--resume" not in sys.argv or not png.exists():
        scene.render.filepath = str(png)
        bpy.ops.render.render(write_still=True)
    source = Image.open(png)
    for square in squares:
        x, y, w, h = rects[square]
        sprite = source.crop((CX + x, CY + y, CX + x + w, CY + y + h))
        # Soft contact shade follows only the object's matte, never a rectangular plane.
        alpha = sprite.getchannel("A")
        shade = Image.new("RGBA", sprite.size, (43, 36, 28, 0))
        soft = alpha.filter(ImageFilter.GaussianBlur(1.2)).point(lambda value: round(value * .23))
        displaced = Image.new("L", sprite.size, 0)
        displaced.paste(soft, (0, 1))
        shade.putalpha(displaced)
        shade.alpha_composite(sprite)
        sprite = shade
        # The head spans the whole tile. Clip adjacent rendered strips out of its padded box.
        mask = Image.new("L", (w * 4, h * 4), 0)
        points = [((u * CW - x) * 4, (v * CH - y) * 4) for u, v in board["cells"][square]]
        ImageDraw.Draw(mask).polygon(points, fill=255)
        sprite.putalpha(ImageChops.multiply(sprite.getchannel("A"), mask.resize((w, h), Image.Resampling.LANCZOS)))
        sprites.append((f"{prefix}-{square}", sprite))


for seat, color in enumerate(COLORS):
    rgb = tuple(srgb((color >> shift) & 255) for shift in (16, 8, 0))
    enamel.diffuse_color = (*rgb, 1)
    enamel.node_tree.nodes.get("Principled BSDF").inputs["Base Color"].default_value = (*rgb, 1)
    render_frames(f"owner-{seat}", DEEDS)

for obj in badges:
    obj.hide_render = True


def hotel(square):
    # A real capsule, with softly beveled edges and a flat porcelain top.
    along, depth = dimensions(square)
    radius, half = depth * .030, along * .27
    outline = []
    for end, offset in ((0, half - radius), (math.pi, -half + radius)):
        for step in range(17):
            angle = end - math.pi / 2 + math.pi * step / 16
            outline.append((offset + math.cos(angle) * radius, math.sin(angle) * radius))
    center_x, center_y = xy(square, .5, .95)
    horizontal = board["tile_side"](square) in ("bottom", "top")
    vertices = []
    for z, shrink in ((.047, 1), (.053, .96)):
        for x, y in outline:
            px, py = (x, y) if horizontal else (y, x)
            vertices.append((center_x + px * shrink, center_y + py * shrink, z))
    n = len(outline)
    faces = [(i, (i + 1) % n, (i + 1) % n + n, i + n) for i in range(n)]
    faces += [tuple(range(n - 1, -1, -1)), tuple(range(n, 2 * n))]
    mesh = bpy.data.meshes.new(f"Hotel capsule {square}")
    mesh.from_pydata(vertices, [], faces)
    mesh.update()
    obj = bpy.data.objects.new(f"Hotel capsule {square}", mesh)
    bpy.context.collection.objects.link(obj)
    obj.data.materials.append(porcelain)
    bevel = obj.modifiers.new("Porcelain edge", "BEVEL")
    bevel.width, bevel.segments = .0012, 3
    obj.modifiers.new("Porcelain normals", "WEIGHTED_NORMAL")
    return obj


for level in range(1, 6):
    buildings = []
    for square in STREETS:
        if level == 5:
            buildings.append(hotel(square))
        else:
            along, depth = dimensions(square)
            for house in range(level):
                x, y = xy(square, .5 + (house - (level - 1) / 2) * .16, .95)
                bpy.ops.mesh.primitive_uv_sphere_add(segments=24, ring_count=16, radius=along * .052, location=(x, y, .047))
                obj = bpy.context.object
                obj.name = f"Porcelain house {square}-{house}"
                obj.scale.z = .36
                obj.data.materials.append(porcelain)
                for face in obj.data.polygons:
                    face.use_smooth = True
                buildings.append(obj)
    render_frames(f"houses-{level}", STREETS)
    for obj in buildings:
        bpy.data.objects.remove(obj, do_unlink=True)

# Shelf packing with two transparent pixels between frames prevents texture bleeding.
atlas_width = 1024
x, y, row_height = 2, 2, 0
packed = []
for name, sprite in sprites:
    w, h = sprite.size
    if x + w + 2 > atlas_width:
        x, y, row_height = 2, y + row_height + 4, 0
    packed.append((name, sprite, x, y))
    x += w + 4
    row_height = max(row_height, h)
atlas = Image.new("RGBA", (atlas_width, y + row_height + 2), (0, 0, 0, 0))
frames = {}
for name, sprite, x, y in packed:
    w, h = sprite.size
    atlas.paste(sprite, (x, y))
    frames[name] = {"frame": {"x": x, "y": y, "w": w, "h": h}, "rotated": False, "trimmed": False,
                    "spriteSourceSize": {"x": 0, "y": 0, "w": w, "h": h}, "sourceSize": {"w": w, "h": h}}
atlas.save(ASSETS / "deed-layers.webp", "WEBP", quality=96, method=6)
(ASSETS / "deed-layers.json").write_text(json.dumps({"frames": frames, "meta": {"image": "deed-layers.webp", "size": {"w": atlas.width, "h": atlas.height}, "scale": "1"}}, separators=(",", ":")))
print(f"Baked {len(frames)} Blender deed frames into {atlas.width}x{atlas.height}")
